include/rfl/internal/bind_to_tuple.hpp
include/rfl/parsing/Parser.hpp
tests/json/CMakeLists.txt
tests/json/test_std_ref.cpp
tests/json/test_std_ref.hpp
tests/json/tests.cpp

Only for serialization - similarly to pointers, this should not be used for deserialization.
As discussed https://github.com/getml/reflect-cpp/pull/20#issuecomment-1857491501 this requires changing the implementation of bind_to_tuple, since std::ref() collapses on a std::reference_wrapper.
Checked tests run under g++ 11.4.0
Formatted additions with clang-format 16.0.0

Serialization of std::reference_wrapper

---

include/rfl/internal/no_duplicate_field_names.hpp

Fixes the following compile error:
```
external/com_github_getml_reflect_cpp/include/rfl/internal/no_duplicate_field_names.hpp:16:26: error: ambiguous overload for 'operator==' (operand types are 'int' and 'const std::tuple_size<std::tuple<rfl::Field<rfl::internal::StringLiteral<12>{std::array<char, 11>{"op_history"}}, const elixir::utils::RingArray<double>*>, rfl::Field<rfl::internal::StringLiteral<5>{std::array<char, 4>{"sum"}}, const double*> > >')
16 |         if constexpr (_i == num_fields) {
```
Seems `num_fields` is set to `std::tuple_size` by mistake. It should be `std::tuple_size_v`

Fix type error in `no_duplicate_field_names`

---

include/rfl/Result.hpp
include/rfl/internal/StringLiteral.hpp

These are two tiny changes that fix compilation errors on the clang / Darwin platform.
1. Add default initialization to `arr_` in StringLiteral.hpp #48 
2. Add include for `<string>` in Result.hpp

Two tiny changes to fix compilation errors on the clang / Dawwin platform.

---

include/rfl/internal/enums/get_enum_names.hpp
include/rfl/internal/get_field_names.hpp
include/rfl/internal/get_type_name.hpp

This fixes https://github.com/getml/reflect-cpp/issues/56.
As described in that issue, the `function_name()` obtained from `std::source_location` on clang on windows does not include template parameters, which means the tricks used by the library to determine names automatically just don't work. However, `__PRETTY_FUNCTION__` does contain the template parameters and gives the exact string we wanted.
This works whether running clang directly on Windows or whether via `clang-cl`, since both `__clang__` and `_MSC_VER` are defined in either case.
I did a few tests of some basic functionality of the library and everything seemed to work as expected now.

Make library work on clang on windows

---

include/rfl/parsing/Parser.hpp
include/rfl/parsing/Parser_wstring.hpp
tests/bson/test_wstring.cpp
tests/bson/test_wstring.hpp
tests/bson/tests.cpp
tests/cbor/test_wstring.cpp
tests/cbor/test_wstring.hpp
tests/cbor/tests.cpp
tests/flexbuffers/test_wstring.cpp
tests/flexbuffers/test_wstring.hpp
tests/flexbuffers/tests.cpp
tests/json/test_wstring.cpp
tests/json/test_wstring.hpp
tests/json/tests.cpp
tests/xml/test_wstring.cpp
tests/xml/test_wstring.hpp
tests/xml/tests.cpp
tests/yaml/test_wstring.cpp
tests/yaml/test_wstring.hpp
tests/yaml/tests.cpp

Adds a conversion to/fro wstring while parsing using wcstombs/mbstowcs. Due to the differences between various implementations and the C++ standard depreciating wstring_convert, this is the best solution I could think of. Let me know if there are potentially better ideas/implementations.
If I have missed anything, do let me know - this is a compicated repo! 😸

feat: add support for parsing std::wstrings

---

include/rfl/parsing/Parser_wstring.hpp

Hiya. I made a mistake when doing the original wstring parser. It would crash when trying to construct a wstring for reading due to the parameters being inverted. I tested it on MSVC which worked fine, but when setting it up on Clang it crashed.

fix: handle wstrings being different lengths and constructed correctly

---

README.md
docs/enums.md
include/rfl.hpp
include/rfl/enums.hpp
include/rfl/internal/enums/Names.hpp
tests/json/test_enum.cpp
tests/json/test_flag_enum.cpp

In the same spirit as https://github.com/getml/reflect-cpp/pull/59, I'd like reflect-cpp to expose general-purpose enum reflection utilities (since it already knows how to do this internally), without having to depend on `rfl::internal` or implement things myself.
This PR adds four functions in a new `rfl/enums.hpp` file:
* `rfl::enum_to_string(enum)` and `rfl::string_to_enum<EnumType>(string)` are simple wrappers around the existing internal functions.
* `rfl::get_enumerators<EnumType>()` gives back a named tuple of enumerator names/values, while `rfl::get_enumerator_array<EnumType>` gives back the same data as an `std::array` of pairs (the main advantage of this one being that it can be `constexpr`).
Example:
```
enum class Color { red, green, blue };
get_enumerators<EnumType>() == …
```

Add helpers for inspecting enum types

---

include/rfl/NamedTuple.hpp
tests/json/test_apply.cpp

58f1e41c830d2e598415e480939e38df3a76f785 changed the parameter type of the named tuple `apply` method from `F&&` to `const F&`, but this prevents it from being used with non-const objects. There is certainly no reason to disallow this (my fault for not adding a test).

undo change of parameter type in `NamedTuple::apply`

---

CMakeLists.txt

`BUILD_SHARED_LIBS` is the standard cmake variable to indicate if output should be shared libraries, so this should be used to streamline standalone builds.  To not break existing integrations and to make inclusion (eg as submodule) easier this patch leaves `REFLECTCPP_BUILD_SHARED` in place but default-initializes it with the value of `BUILD_SHARED_LIBS`.

Use BUILD_SHARED_LIBS as default value for REFLECTCPP_BUILD_SHARED

---

CMakeLists.txt
reflectcpp-config.cmake.in

This makes reflectcpp installable by cmake and adds a config module, so that it can be used like any other cmake package
```
find_package(reflectcpp REQUIRED)
target_link_libraries(MY_TARGET reflectcpp::reflectcpp)
```

Add cmake config module

---

reflectcpp-config.cmake.in

This fixes a typo in the call to check_required_components.
Without this fix it is possible for a consumer to require a component that does not exist without getting an error from cmake.
Eg
```
find_package(reflectcpp REQUIRED COMPONENTS does-not-exist)
```
would succeed, but should result in an error.

reflectcpp-config.cmake.in: Fix typo in check_required_components

---

.gitignore
include/rfl/internal/bind_to_tuple.hpp
include/rfl/internal/num_fields.hpp
tests/json/test_inheritance2.cpp
tests/json/test_inheritance2.hpp
tests/json/test_view.cpp
tests/json/tests.cpp

Resolves <https://github.com/getml/reflect-cpp/issues/82>
Please squash merge this PR.

Support one-level inheritance cases

---

include/rfl/parsing/NamedTupleParser.hpp

In 0.8.0.0 and 0.9.0, I met a compilation error on older msvc(19.36) followings:
```
include\rfl\parsing\NamedTupleParser.hpp(99,51): error C2653: 'T': is not a class or namespace name [test_package.vcxproj]
include\rfl\parsing\NamedTupleParser.hpp(90,23): message : This diagnostic occurred in the compiler generated function 'rfl::parsing::schema::Type rfl::parsing::NamedTupleParser<R,W,_ignore_empty_containers,_all_required,FieldTypes...>::to_schema(std::map<std::string,rfl::parsing::schema::Type,std::less<std::string>,std::allocator<std::pair<const std::string,rfl::parsing::schema::Type>>> 
```
I confirmed it is caused by the line in NamedTupleParser.hpp.
```
using F = std::tuple_element_t<_i, typename T::Fields>;
```
This PR try to fix this compilation error.
Please review and merge it …

fix older msvc(19.36) compilation error

---

include/rfl/json/Reader.hpp
include/rfl/json/Writer.hpp
tests/json/test_integers.cpp

Json reader and writer now handle 64bit ints correctly, no longer casts them to a i32. Added test checking full int range

[fix] 64bit int support for json

---

benchmarks/json/canada.cpp

This doesn't really make simdjson any faster than BSON or other formats, but it does bring it back in line with my expectations around performance :) After this, canada.json is the same or faster than yyjson on my machine (but only by pennies!), and remains faster on the other benchmarks.
The two changes that made the difference:
1. Inlining the deserialization methods. On Demand is explicitly designed to take advantage of inlining.
2. Reading the coordinate tuple [1,2] with an iterator instead of indexing it as an array.
I also removed some unnecessary boilerplate .value() and .get_array/object() methods.
NOTE: simdjson could get some small perf gains if `rfl::Literal` took a string_view constructor; the fact that it takes a `std::string` means we're forced to allocate every time we see …

simdjson inlining and idiomaticity in benchmark

---

docs/custom_parser.md

For the example to compile, the `ProcessorsType` needs to be passed though to the custom perser's template params?

Fix typo in custom parser docs

---

include/rfl/Size.hpp
include/rfl/json/schema/Type.hpp
src/reflectcpp.cpp
tests/json/test_json_schema_size_validation.cpp

A fix for the incorrect JSON schema being generated for size validated fields.
At first I was just tinkering around with the library and testing its features, and one thing I was interested in is automatic JSON schema generation. I wanted to be sure my strings would be X characters long, and the library had the support for that, but JSON schema generated for such fields is obviously incorrect.
So for the struct:
```
struct TestStruct
{
template<typename T, auto Min, auto Max>
using SizeValidated = rfl::Validator<T, rfl::Size<rfl::Minimum<Min>>, rfl::Size<rfl::Maximum<Max>>>;
SizeValidated<std::string, 1, 2> a;
};
```
generated schema is:
```
{
"$schema": "https://json-schema.org/draft/2020-12/schema",
"$ref": "#/definitions/TestStruct",
"definitions": {
"TestStruct": {
"type": "object", …
```

fix: incorrect json schema for size validated fields

---

docs/custom_parser.md
include/rfl/internal/has_reflection_method_v.hpp
include/rfl/internal/has_reflector.hpp
include/rfl/parsing/Parser_default.hpp
tests/json/test_reflector_read.cpp
tests/json/test_reflector_write.cpp
tests/json/write_and_read.hpp

Changes:
- Separates the `has_reflector` concept into `has_read_reflector` and `has_write_reflector` to allow allow Reflector types to be just readable, just writable, or both readable and writable.
- Adds test cases. The tests are slightly altered from the original `test_reflector` implementation. They now use a small class hierarchy (`Person` and `Parent`) with fields in each class, which is not supported by default. The Reflector implementation in the tests flattens the hierarchy.  Test cases for Reflector implementations with only the `to` and only the `from` method are present.
- Adds a paragraph to the docs mentioning the user-facing changes.
Fixes issue: #150

feat: optional to/from methods on Reflector. (#150)

---

README.md

The `libbson` link the README pointed to was the archived version of `libbson`. After struggling to compile things for a while, I realized `reflect-cpp` expects a recent enough version of `libbson` that it needs to originate from https://github.com/mongodb/mongo-c-driver.

Update README.md to reflect expected libbson version

---

CMakeLists.txt
benchmarks/all/CMakeLists.txt
benchmarks/json/CMakeLists.txt
tests/bson/CMakeLists.txt
tests/cbor/CMakeLists.txt
tests/flexbuffers/CMakeLists.txt
tests/json/CMakeLists.txt
tests/json_c_arrays_and_inheritance/CMakeLists.txt
tests/msgpack/CMakeLists.txt
tests/toml/CMakeLists.txt
tests/xml/CMakeLists.txt
tests/yaml/CMakeLists.txt

Cuts tests and benchmarks build time by ~30%
Does not affect library users

add simple precompiled headers

---

include/rfl/parsing/Parser_string_view.hpp

Fix endless recursion in `std::string_view` writer: the `write()` should use `std::string`, not `std::string_view` again

Fix endless recursion in std::string_view writer

---

include/rfl/PatternValidator.hpp

Fix wrong header filename for ctre library

---

include/rfl/parsing/call_destructors_where_necessary.hpp

Pull request for missing include from: https://github.com/getml/reflect-cpp/issues/235
Tested single includes:
`#include <rfl/json/write.hpp>`
`#include <rfl/json/read.hpp>`

Added missing get.hpp include to call_desctructors_where_necessary.hpp

---

include/rfl/parsing/call_destructors_where_necessary.hpp

There was a compilation error when building on 32 bit platforms. I assume it is because `std::size_t` used for `std::array<T, std::size_t N>` is an `unsigned long` on 64 bit and `unsigned int` on 32 bit. 
See this for a quick demonstration: https://godbolt.org/z/xcrdjM5Ks

Fixed issue where 32 bit compilation cause template type deduction fail

---

README.md

Just spotted this on the new docs site. The "Maintained? yes" badge links to a different GitHub repository. This PR updates the link to point to this repository instead.
---
Since this is my first time here, just wanted to say thank you for your work on this library. I've been using it extensively over the past few months in conjunction with custom code generation for cross-language state synchronization and IPC, and have been blown away by the developer experience. reflect-cpp is an effective and highly usable library, and is by far the best solution I've seen for my use cases.

Fix link to commit activity in readme

---

include/rfl/TaggedUnion.hpp
tests/json/test_tagged_union5.cpp

Following @liuzicheng1987 advice (https://github.com/getml/reflect-cpp/issues/272#issuecomment-2492386937), I had a hard time converting my code in order to have it work in TaggedUnion.hpp.
Note sure at all that it is OK?
Best regards

Add operator== to TaggedUnion.hpp

---

include/rfl/Timestamp.hpp

Original
---
Timestamp: Replace `strptime` with `std::get_time` for better compatibility
The `strptime` function is a POSIX extension, not universally supported by all compilers (e.g., MSVC). Replacing it with `std::get_time`, which is part of the C++ standard, improves cross-platform compatibility without sacrificing functionality.
Edit
---
`std::get_time` has poor performance compared to `strptime`. My issue was that MinGW failed to compile `reflect-cpp` due to the lack of `strptime`. A more precise solution is to extend the existing workaround to cover MinGW, while keeping `strptime` for better performance on supported platforms.

Timestamp: Update workaround to support MinGW alongside MSVC

---

include/rfl/json/read.hpp

Hi, this is a very simple PR to change rfl::json::read to use std::string_view instead of std::string. This allows JSON to be read in a zero-copy way when e.g. one has a const char*. Because std::string_view can be implicitly constructed from std::string, the change should have no impact on existing user code.
I verified that all json parser tests pass with this change.

Json read string view

---

CMakeLists.txt

Hello,
I propose this change to enable building reflect-cpp with Yocto.
Without this change, the following error occurs during the build process:
```
ERROR: reflect-cpp-0.16.0-r0 do_package_qa: QA Issue: -dev package reflect-cpp-dev contains non-symlink .so '/usr/lib/libreflectcpp.so' [dev-elf]
ERROR: reflect-cpp-0.16.0-r0 do_package_qa: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /workdir/tmp/work/cortexa55-xware-linux/reflect-cpp/0.16.0/temp/log.do_package_qa.1139088
ERROR: Task (/workdir/layers/meta-xhello/recipes-core/reflect-cpp/reflect-cpp_0.16.0.bb:do_package_qa) failed with exit code '1'
```
With this change, the package builds correctly with the proper SOVERSION. Yocto can locate the original .so file in the main package and create a symlink in …

Add versioning in CMake for shared library

---

include/rfl/msgpack/Writer.hpp

Once again, when adding the latest version of the rfl library to the project, this one include was missing and had to be added manually. The time has come to finally add it.

Add missing `Bytestring.hpp` include in `msgpack\Writer.hpp`

---

include/rfl/parsing/Parser_default.hpp
tests/json/test_movable.cpp

This eliminates an unnecessary copy of a temporary variable which prohibits use of a move-only construction of reflection-types.

Parser_default: Move temporary variable instead of copying

---

docs/replace.md

This probably doesn't look as expected: https://rfl.getml.com/replace/

docs: remove superfluous backtick in replace.md

---

include/rfl/yaml/Writer.hpp
tests/yaml/test_double.cpp

Make sure that floats are serialized properly in YAML; fixes #363

---

include/rfl/Result.hpp

I found this issue while compiling with clang 20.1.0.
Header <new> is needed by `std::launder`

add missing include <new>

---

include/rfl/parsing/Parser_optional.hpp
tests/generic/test_optional.cpp

Fix bugging disallowing optionals to hold items without copy constructors

---

docs/enums.md
include/rfl/enums.hpp
include/rfl/internal/enums/Names.hpp
include/rfl/internal/enums/get_enum_names.hpp
tests/generic/test_enum.cpp
tests/generic/test_enum_range.cpp
tests/generic/test_enum_range_min_max.cpp
tests/generic/test_enum_range_size.cpp

Currently, the supported value range in reflect-cpp is 0 to 127. This change aims to allow users to customize the enum range.
Enum values must be in the range `[RFT_ENUM_RANGE_MIN, RFT_ENUM_RANGE_MAX]`. If the range is not specified, the
default range is `[0, 127]`.
- You can specify a custom range for the all enum values by defining `RFT_ENUM_RANGE_MIN` and `RFT_ENUM_RANGE_MAX`
before including the reflect-cpp header:
#define RFL_ENUM_RANGE_MIN -128
#define RFL_ENUM_RANGE_MAX 128
#include <rfl.hpp>
- You can specify a custom range for a specific enum by defining the specialization `rfl::config::enum_range` for
the enum type :
enum class Color { yellow = 200, purple = 300, orange = 400 };
template <>
struct rfl::config::enum_range<Color> {
static constexpr int min = 200;
static constexpr …

Add enum range support with customizable min and max values

---

docs/rfl_ref.md
include/rfl/Box.hpp
include/rfl/parsing/Parser_box.hpp
tests/generic/test_box.cpp

Possible implementation for: https://github.com/getml/reflect-cpp/issues/397
With an explicit type `rfl::CopyableBox` that can be substituted in for `rfl::Box`, that enables easy copying of data.

Possible implementation for #397: Allow Boxes to conditionally be copyable with an explicit option

---

include/rfl/Bytestring.hpp
include/rfl/avro/Reader.hpp
include/rfl/avro/Writer.hpp
include/rfl/bson/Writer.hpp
include/rfl/flexbuf/Writer.hpp
include/rfl/internal/enums/StringConverter.hpp
include/rfl/msgpack/Writer.hpp

This is a fix for the regression introduced with the Bytestring std::vector replacement.
It was serialized as a vector of enums instead of binary data.
I haven't found a cleaner way other than making a fake type to avoid it being treated as `std::vector<T>`.
Also, I can make write_and_read return serialized size, so that such regression can be caught by the test_bytestring and explicit size check in it

fix bytestring being serialized as vector of flag enums

---

include/rfl/cbor/read.hpp
include/rfl/ubjson/read.hpp
tests/cbor/test_error_messages.cpp
tests/json/test_error_messages.cpp
tests/ubjson/test_error_messages.cpp

This PR is a working illustration of the problem reported in #429.
The current implementation using `jsoncons::cbor::decode_cbor()` always throws when there is a fundamental CBOR decoding error, as opposed to a mere structure reflection mismatch.

Test for JSON & CBOR encoding error handling

---

include/rfl/cbor/Writer.hpp
tests/cbor/test_integers.cpp

A fix for cbor encoding; unsigned integers were being emitted as signed ints.

Fix cbor encoding for uint64_t's

---

include/rfl/Binary.hpp
include/rfl/Box.hpp
include/rfl/Description.hpp
include/rfl/Field.hpp
include/rfl/Flatten.hpp
include/rfl/Tuple.hpp
include/rfl/Validator.hpp
include/rfl/Variant.hpp

Repeating ourseleves provides no value and it is verbose

Dont repeat class names template arguements

---

include/rfl/OneOf.hpp
include/rfl/Variant.hpp
include/rfl/parsing/Parser_tagged_union.hpp

I met a macro confilict.
It's in `resolv.h` in linux. In which there is a macro called `_res`.
So I renamed  _res to _result to avoid macro conflict.
BTW, just curious, why do you name all variables with a prefix underline? These names are likely to be used in system headers.

rename _res to _result to avoid macro conflict

---

CMakeLists.txt

What is the problem ?
When using reflect-cpp without installing it, the CMake target reflectcpp::reflectcpp is not automatically provided. This namespaced target is only made available through installation.
Abstract Example:
```
if(MY_LIB_BUILD_DEPS)
FetchContent_Declare(
reflectcpp
GIT_REPOSITORY https://github.com/getml/reflect-cpp.git
GIT_TAG 2a0fdeabe35bdab0e07e05d4f869ca88bd6d2b8c
OVERRIDE_FIND_PACKAGE
)
// Here we get just reflectcpp
FetchContent_MakeAvailable(reflectcpp)
// Manually create an alias to have a common interface
add_library(reflectcpp::reflectcpp ALIAS reflectcpp)
else()
// Here we get the relfectcpp::reflectcpp target 
find_package(reflectcpp REQUIRED)
endif()
...
target_link_libraries(${PROJECT_NAME} PRIVATE reflectcpp::reflectcpp)
```
What does this solve ?
This …

make sure reflectcpp library namespace is also available when not installing

---

include/rfl/json/read.hpp
tests/json/test_error_messages.cpp

Add error message for json read

---

include/rfl/parsing/Parser_rfl_variant.hpp
tests/json/test_add_tag_to_rfl_variant.cpp

Added a test. Needed to change the test to emplace each element rather than initializer_list due to the non-copyable element.

Fix bug reading with 'tagged' variants when a variant is non-copyable

---

docs/custom_parser.md
docs/docs-readme.md
include/rfl/num_fields.hpp
tests/README.md
tests/json_c_arrays_and_inheritance/test_inheritance2.cpp

- "Fixes" #451 by making `rfl::num_fields` "public" by moving it out of the `rfl::internal` namespace
- Documents my use-case for `rfl::num_fields` in `rfl::Reflector` validation.
- Update `tests/README.md` with easier execution method

Make `rfl::num_fields` public

---

include/rfl.hpp
include/rfl/Bytestring.hpp
include/rfl/Vectorstring.hpp
include/rfl/avro/Reader.hpp
include/rfl/avro/Writer.hpp
include/rfl/bson/Reader.hpp
include/rfl/bson/Writer.hpp
include/rfl/capnproto/Reader.hpp
include/rfl/capnproto/Writer.hpp
include/rfl/cbor/Reader.hpp
include/rfl/cbor/Writer.hpp
include/rfl/flexbuf/Reader.hpp
include/rfl/flexbuf/Writer.hpp
include/rfl/generic/Reader.hpp
include/rfl/msgpack/Reader.hpp
include/rfl/msgpack/Writer.hpp
include/rfl/parsing/Parser.hpp
include/rfl/parsing/Parser_vectorstring.hpp
include/rfl/parsing/VectorParser.hpp
include/rfl/parsing/schema/Type.hpp
include/rfl/ubjson/Reader.hpp
include/rfl/ubjson/Writer.hpp
src/rfl/avro/to_schema.cpp
src/rfl/capnproto/to_schema.cpp
src/rfl/json/to_schema.cpp
tests/bson/test_vectorstring.cpp
tests/cbor/test_vectorstring.cpp
tests/msgpack/test_vectorstring.cpp
tests/ubjson/test_vectorstring.cpp

Serialize/Deserialize `vector<char>` as bytestring

---

include/rfl/Object.hpp

I want to extend the [jwt-cpp library](https://github.com/Thalhammer/jwt-cpp) so it has reflect-cpp compatibility. The interfaces exposed by reflect-cpp are already almost compatible with the traits expected by jwt-cpp, but a small addition to rfl::Object is needed so that it exposes a `std::size_t count(const key_type& key) const` method. This PR adds that methd.

Add interfaces for jwt-cpp compatibility

---

include/rfl/Result.hpp
include/rfl/parsing/MapReader.hpp
include/rfl/parsing/NamedTupleParser.hpp
include/rfl/parsing/Parser_default.hpp
include/rfl/parsing/Parser_rfl_variant.hpp
include/rfl/parsing/Parser_variant.hpp

Hello!
This isn't really a significant change, but it helps speed up `rfl::json::read<rfl::Generic>` almost twice in the release build (at least in the benchmarked case).
Sorry for not using your benchmark suite here, I had problems getting the `vcpkg` dependencies properly compiled with GCC15 that ships with my system.
I also tried to look into improving the debug build performance of `rfl::to_generic`, but couldn't find anything to improve there, at least not as simple.
Before:
```
--------------------------------------------------------------
Benchmark                    Time             CPU   Iterations
--------------------------------------------------------------
read_struct               95.5 ns         94.4 ns      7332806
read_generic               645 ns          637 ns …
```

Better forwarding to improve read performance a little

---

src/yyjson.c

```
./src/yyjson.c:4308:18: warning: ‘f64_pow10_table’ defined but not used [-Wunused-const-variable=]
4308 | static const f64 f64_pow10_table[] = {
|                  ^~~~~~~~~~~~~~~
```

Avoid defined but not used warning in `yyjson.c`
